//! Clarifying Question Types
//!
//! Data structures for the TUI Q&A system where AI can ask structured
//! clarifying questions that are rendered as interactive modal overlays.
//!
//! Includes AT-CoT (Ambiguity Type-Chain of Thought) metadata for improved
//! disambiguation based on arXiv:2504.12113.

use serde::{Deserialize, Serialize};

/// Ambiguity types from AT-CoT paper (arXiv:2504.12113)
///
/// These types categorize the nature of ambiguity in user queries to enable
/// more targeted clarifying questions.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum AmbiguityType {
    /// Terms with multiple meanings (e.g., "cache" could be LRU, LFU, Redis)
    /// User action: User clarifies the MEANING of unclear terms
    Semantic,

    /// Request too specific, may need broader scope
    /// User action: User BROADENS overly specific request
    /// Example: "Add validation to login form" → User wants ALL forms
    Generalize,

    /// Request too broad, needs concrete constraints
    /// User action: User NARROWS overly broad request
    /// Example: "Optimize the code" → User specifies "database query performance"
    Specify,
}

impl AmbiguityType {
    /// Get emoji representation for UI display
    pub fn to_emoji(&self) -> &'static str {
        match self {
            Self::Semantic => "🔍",   // Magnifying glass for meaning
            Self::Generalize => "📐", // Triangle for broadening
            Self::Specify => "🎯",    // Target for narrowing
        }
    }

    /// Get human-readable name
    pub fn to_display_name(&self) -> &'static str {
        match self {
            Self::Semantic => "Semantic",
            Self::Generalize => "Generalize",
            Self::Specify => "Specify",
        }
    }
}

/// AT-CoT ambiguity analysis for a query
///
/// This metadata is generated by the AI BEFORE creating clarifying questions
/// to improve question quality through ambiguity type prediction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AmbiguityAnalysis {
    /// Predicted ambiguity types for this query
    pub predicted_types: Vec<AmbiguityType>,

    /// AI's reasoning for these predictions
    pub reasoning: String,
}

/// A single clarifying question with selectable options
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClarifyingQuestion {
    /// Unique identifier for tracking
    pub id: String,
    /// The question text to display
    pub question: String,
    /// Short label for the question (max 12 chars)
    pub header: String,
    /// Available options to choose from
    pub options: Vec<QuestionOption>,
    /// Whether multiple options can be selected
    pub multi_select: bool,

    /// Optional ambiguity type for this question (AT-CoT)
    /// Used to track which ambiguity type this question addresses
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ambiguity_type: Option<AmbiguityType>,
}

/// An option within a clarifying question
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionOption {
    /// Unique identifier for this option
    pub id: String,
    /// Short label (1-5 words)
    pub label: String,
    /// Optional longer description
    pub description: Option<String>,
}

/// A block of clarifying questions from an AI response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionBlock {
    /// Optional ambiguity analysis (AT-CoT)
    /// Predicted ambiguity types and reasoning for this query
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ambiguity_analysis: Option<AmbiguityAnalysis>,

    /// The questions to ask
    pub questions: Vec<ClarifyingQuestion>,
}

/// UI state for answering questions in the TUI
#[derive(Debug, Clone, Default)]
pub struct QuestionAnswerState {
    /// Index of the current question being answered
    pub current_question_idx: usize,
    /// Selected options for each question (per question, per option)
    pub selected_options: Vec<Vec<bool>>,
    /// Whether "Other" is selected for each question
    pub other_selected: Vec<bool>,
    /// Custom text entered for "Other" option (per question)
    pub other_text: Vec<String>,
    /// Current cursor position within options
    pub cursor_idx: usize,
    /// Whether user is typing in the "Other" text field
    pub editing_other: bool,
}

impl QuestionAnswerState {
    /// Create a new state initialized for the given questions
    pub fn new(questions: &QuestionBlock) -> Self {
        let num_questions = questions.questions.len();
        let selected_options = questions
            .questions
            .iter()
            .map(|q| vec![false; q.options.len()])
            .collect();

        Self {
            current_question_idx: 0,
            selected_options,
            other_selected: vec![false; num_questions],
            other_text: vec![String::new(); num_questions],
            cursor_idx: 0,
            editing_other: false,
        }
    }

    /// Get total number of selectable items for current question (options + "Other")
    pub fn total_items(&self, questions: &QuestionBlock) -> usize {
        if let Some(q) = questions.questions.get(self.current_question_idx) {
            q.options.len() + 1 // +1 for "Other"
        } else {
            1
        }
    }

    /// Check if cursor is on the "Other" option
    pub fn is_cursor_on_other(&self, questions: &QuestionBlock) -> bool {
        if let Some(q) = questions.questions.get(self.current_question_idx) {
            self.cursor_idx >= q.options.len()
        } else {
            false
        }
    }

    /// Toggle selection at current cursor position
    pub fn toggle_current(&mut self, questions: &QuestionBlock) {
        let q_idx = self.current_question_idx;
        let cursor_idx = self.cursor_idx;

        if let Some(q) = questions.questions.get(q_idx) {
            if cursor_idx < q.options.len() {
                // Toggle regular option
                if let Some(selected) = self.selected_options.get_mut(q_idx) {
                    if q.multi_select {
                        // Multi-select: just toggle
                        if let Some(opt) = selected.get_mut(cursor_idx) {
                            *opt = !*opt;
                        }
                    } else {
                        // Single select: clear all first, then set the one
                        for s in selected.iter_mut() {
                            *s = false;
                        }
                        if let Some(opt) = selected.get_mut(cursor_idx) {
                            *opt = true;
                        }
                    }
                }
                // Also clear "Other" selection in single-select mode
                if !q.multi_select
                    && let Some(other) = self.other_selected.get_mut(q_idx)
                {
                    *other = false;
                }
            } else {
                // Toggle "Other"
                let is_multi_select = q.multi_select;

                if !is_multi_select {
                    // Single select: clear options first
                    if let Some(selected) = self.selected_options.get_mut(q_idx) {
                        for s in selected.iter_mut() {
                            *s = false;
                        }
                    }
                }

                // Now toggle "Other"
                if let Some(other) = self.other_selected.get_mut(q_idx) {
                    if is_multi_select {
                        *other = !*other;
                    } else {
                        *other = true;
                    }
                }
            }
        }
    }

    /// Move cursor up
    pub fn cursor_up(&mut self) {
        if self.cursor_idx > 0 {
            self.cursor_idx -= 1;
        }
    }

    /// Move cursor down
    pub fn cursor_down(&mut self, questions: &QuestionBlock) {
        let max = self.total_items(questions).saturating_sub(1);
        if self.cursor_idx < max {
            self.cursor_idx += 1;
        }
    }

    /// Move to next question
    pub fn next_question(&mut self, questions: &QuestionBlock) -> bool {
        if self.current_question_idx + 1 < questions.questions.len() {
            self.current_question_idx += 1;
            self.cursor_idx = 0;
            self.editing_other = false;
            true
        } else {
            false // No more questions
        }
    }

    /// Move to previous question
    pub fn prev_question(&mut self) -> bool {
        if self.current_question_idx > 0 {
            self.current_question_idx -= 1;
            self.cursor_idx = 0;
            self.editing_other = false;
            true
        } else {
            false
        }
    }

    /// Check if all questions have been answered (at least one selection each)
    pub fn all_answered(&self, questions: &QuestionBlock) -> bool {
        for (i, _q) in questions.questions.iter().enumerate() {
            let has_option_selected = self
                .selected_options
                .get(i)
                .map(|opts| opts.iter().any(|&s| s))
                .unwrap_or(false);
            let has_other_selected = self.other_selected.get(i).copied().unwrap_or(false);
            let has_other_text = self
                .other_text
                .get(i)
                .map(|t| !t.trim().is_empty())
                .unwrap_or(false);

            // Valid if: any option selected, or "Other" selected with text
            if !(has_option_selected || has_other_selected && has_other_text) {
                return false;
            }
        }
        true
    }

    /// Check if current question is on the last question
    pub fn is_last_question(&self, questions: &QuestionBlock) -> bool {
        self.current_question_idx + 1 >= questions.questions.len()
    }

    /// Get current "Other" text for current question
    pub fn current_other_text(&self) -> &str {
        self.other_text
            .get(self.current_question_idx)
            .map(|s| s.as_str())
            .unwrap_or("")
    }

    /// Append character to current "Other" text
    pub fn append_other_char(&mut self, c: char) {
        if let Some(text) = self.other_text.get_mut(self.current_question_idx) {
            text.push(c);
        }
    }

    /// Remove last character from current "Other" text
    pub fn backspace_other(&mut self) {
        if let Some(text) = self.other_text.get_mut(self.current_question_idx) {
            text.pop();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_questions() -> QuestionBlock {
        QuestionBlock {
            ambiguity_analysis: None, // Backward compatible - no AT-CoT metadata
            questions: vec![
                ClarifyingQuestion {
                    id: "q1".to_string(),
                    question: "Which auth method?".to_string(),
                    header: "Auth".to_string(),
                    multi_select: false,
                    ambiguity_type: None, // Backward compatible
                    options: vec![
                        QuestionOption {
                            id: "a".to_string(),
                            label: "JWT".to_string(),
                            description: Some("Stateless tokens".to_string()),
                        },
                        QuestionOption {
                            id: "b".to_string(),
                            label: "Sessions".to_string(),
                            description: None,
                        },
                    ],
                },
                ClarifyingQuestion {
                    id: "q2".to_string(),
                    question: "Which features?".to_string(),
                    header: "Features".to_string(),
                    multi_select: true,
                    ambiguity_type: None, // Backward compatible
                    options: vec![
                        QuestionOption {
                            id: "f1".to_string(),
                            label: "Logging".to_string(),
                            description: None,
                        },
                        QuestionOption {
                            id: "f2".to_string(),
                            label: "Caching".to_string(),
                            description: None,
                        },
                    ],
                },
            ],
        }
    }

    #[test]
    fn test_state_initialization() {
        let questions = sample_questions();
        let state = QuestionAnswerState::new(&questions);

        assert_eq!(state.current_question_idx, 0);
        assert_eq!(state.selected_options.len(), 2);
        assert_eq!(state.selected_options[0].len(), 2);
        assert_eq!(state.selected_options[1].len(), 2);
        assert_eq!(state.other_selected.len(), 2);
        assert_eq!(state.other_text.len(), 2);
    }

    #[test]
    fn test_single_select_toggle() {
        let questions = sample_questions();
        let mut state = QuestionAnswerState::new(&questions);

        // Select first option
        state.toggle_current(&questions);
        assert!(state.selected_options[0][0]);
        assert!(!state.selected_options[0][1]);

        // Move to second and select - should deselect first
        state.cursor_down(&questions);
        state.toggle_current(&questions);
        assert!(!state.selected_options[0][0]);
        assert!(state.selected_options[0][1]);
    }

    #[test]
    fn test_multi_select_toggle() {
        let questions = sample_questions();
        let mut state = QuestionAnswerState::new(&questions);

        // Move to second question (multi-select)
        state.next_question(&questions);
        assert_eq!(state.current_question_idx, 1);

        // Select both options
        state.toggle_current(&questions);
        state.cursor_down(&questions);
        state.toggle_current(&questions);

        assert!(state.selected_options[1][0]);
        assert!(state.selected_options[1][1]);
    }

    #[test]
    fn test_navigation() {
        let questions = sample_questions();
        let mut state = QuestionAnswerState::new(&questions);

        assert!(state.next_question(&questions));
        assert_eq!(state.current_question_idx, 1);

        assert!(!state.next_question(&questions)); // No more
        assert_eq!(state.current_question_idx, 1);

        assert!(state.prev_question());
        assert_eq!(state.current_question_idx, 0);

        assert!(!state.prev_question()); // Can't go back
        assert_eq!(state.current_question_idx, 0);
    }
}
