// Resolves the local Ollama install's manifest + blob layout. This mirrors
// the Python helpers in `serve.sh` (`discover_models`,
// `find_blob`) so the React app and the existing static PWA can both run
// against this server.

import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const MODEL_LAYER = "application/vnd.ollama.image.model";

export interface ModelEntry {
    /** "family:tag" e.g. "gemma4:e2b" */
    name: string;
    family: string;
    tag: string;
    size: number;
    /** sha256 hex, no "sha256:" prefix */
    digest: string;
    /** Optional absolute URL — when set the client fetches the blob from
     *  here directly instead of going through /api/blob. Used for the
     *  public demo to offload bandwidth to a CDN (R2, Hugging Face). */
    url?: string;
    /** When `url` points at a full Ollama-style blob (text + vision +
     *  audio), set this so the loader doesn't force the text-only path.
     *  Default for HF-style text-only GGUFs: omit (text-only forced). */
    multimodal?: boolean;
    /** Advisory "heavy model" flag — the client renders a ⚠ marker; Load
     *  is not blocked. Mirrors `heavy` in web/src/lib/api.ts. */
    heavy?: boolean;
}

/**
 * Curated public-CDN fallback. Returned when the local Ollama install
 * has no models or `RULLAMA_REMOTE_ONLY=1` forces it. Each entry points
 * at an HF-hosted GGUF — CORS + Range verified working from the browser.
 *
 * These are text-only quants. The multimodal blobs Ollama distributes
 * (text + vision + audio in one file) aren't mirrored anywhere public.
 */
export function huggingfaceModels(): ModelEntry[] {
    return [
        // The Ollama-style multimodal blobs the user has uploaded to R2.
        // Digests match the user's local ~/.ollama/models copies (Q4_K_M
        // generated by Ollama's pipeline — pure Q4_K + Q6_K, no Q5_K
        // surprises) so an existing OPFS cache stays valid.
        // Update the URL hostname if the bucket is bound elsewhere.
        {
            name:       "gemma4:e2b",
            family:     "gemma4",
            tag:        "e2b",
            size:       7162394016,
            digest:     "4e30e2665218745ef463f722c0bf86be0cab6ee676320f1cfadf91e989107448",
            url:        "https://models.brainwires.dev/gemma4-e2b.gguf",
            multimodal: true,
        },
        {
            name:       "gemma4:e4b",
            family:     "gemma4",
            tag:        "e4b",
            size:       9608338848,
            digest:     "4c27e0f5b5adf02ac956c7322bd2ee7636fe3f45a8512c9aba5385242cb6e09a",
            url:        "https://models.brainwires.dev/gemma4-e4b.gguf",
            multimodal: true,
        },
        {
            // Google's 12B (2026-06). Same gemma4 arch, Q4_K_M, text-only
            // (no vision/audio towers). Heavy — advisory ⚠, never blocked.
            name:       "gemma4:12b",
            family:     "gemma4",
            tag:        "12b",
            size:       7381382048,
            digest:     "1278394b693672ac2799eadc9a83fd98259a6a88a40acfb1dcaa6c6fc895a606",
            url:        "https://models.brainwires.dev/gemma4-12b.gguf",
            heavy:      true,
        },
        {
            // QAT (quantization-aware-trained) e2b — Q4_0 text weights, ~3.3 GB
            // (< half the standard e2b). Text-only (QAT towers ship as a separate
            // projector blob, not merged). Same gemma4 forward path.
            name:       "gemma4:e2b-it-qat",
            family:     "gemma4",
            tag:        "e2b-it-qat",
            size:       3349514112,
            digest:     "3646b4c147cd235a44d91df1546d3b7d8e29b547dbe4e1f80856419aa455e6fd",
            url:        "https://models.brainwires.dev/gemma4-e2b-it-qat.gguf",
        },
        {
            // QAT e4b — Q4_0 text weights, 5.15 GB (vs 9.6 GB std). Text-only.
            name:       "gemma4:e4b-it-qat",
            family:     "gemma4",
            tag:        "e4b-it-qat",
            size:       5154939136,
            digest:     "e8b6a059ba86947a44ace84d6e5679795bc41862c25c30513142588f0e9dba1d",
            url:        "https://models.brainwires.dev/gemma4-e4b-it-qat.gguf",
        },
        {
            // QAT 12b — Q4_0 text weights, 6.98 GB (vs 7.38 GB std). Text-only,
            // heavy → advisory ⚠. Needs 12b per-layer KV heads + no-V global attn.
            name:       "gemma4:12b-it-qat",
            family:     "gemma4",
            tag:        "12b-it-qat",
            size:       6975877728,
            digest:     "faff1a63667fac17ac5e777f47114688fcefea96e220e211aaa8d62c2c4561f1",
            url:        "https://models.brainwires.dev/gemma4-12b-it-qat.gguf",
            heavy:      true,
        },
        {
            // e2b @ Q8_0 — 8-bit weights, highest-quality quant. 8.14 GB. Full
            // multimodal blob (text Q8_0 + BF16/F16 towers, census-verified).
            name:       "gemma4:e2b-it-q8_0",
            family:     "gemma4",
            tag:        "e2b-it-q8_0",
            size:       8140140960,
            digest:     "6aade8551d1aecae00d6520d5db327efbef4b96ff92abef353ef6cd8e4e6d589",
            url:        "https://models.brainwires.dev/gemma4-e2b-it-q8_0.gguf",
            multimodal: true,
        },
        {
            // e4b @ Q8_0 — 11.6 GB, full multimodal blob.
            name:       "gemma4:e4b-it-q8_0",
            family:     "gemma4",
            tag:        "e4b-it-q8_0",
            size:       11636104608,
            digest:     "62d767a4c82f7acba2e1da74df317f01ce34b92830712c536260f82acfb63ac9",
            url:        "https://models.brainwires.dev/gemma4-e4b-it-q8_0.gguf",
            multimodal: true,
        },
        {
            // 12b @ Q8_0 — 12.7 GB, text-only (12b builds ship no towers), heavy ⚠.
            name:       "gemma4:12b-it-q8_0",
            family:     "gemma4",
            tag:        "12b-it-q8_0",
            size:       12669645728,
            digest:     "047dae1d7894b9de8f08141e841544e007243290c02df8b39872991d1940c795",
            url:        "https://models.brainwires.dev/gemma4-12b-it-q8_0.gguf",
            heavy:      true,
        },
    ];
}

export function ollamaRoot(): string {
    return process.env.OLLAMA_MODELS || path.join(os.homedir(), ".ollama", "models");
}

function manifestDir() { return path.join(ollamaRoot(), "manifests"); }
function blobDir()     { return path.join(ollamaRoot(), "blobs"); }

function walkFiles(root: string, out: string[] = []): string[] {
    let entries: fs.Dirent[];
    try {
        entries = fs.readdirSync(root, { withFileTypes: true });
    } catch { return out; }
    for (const e of entries) {
        const p = path.join(root, e.name);
        if (e.isDirectory())   walkFiles(p, out);
        else if (e.isFile())   out.push(p);
    }
    return out;
}

/** Discover all locally-installed Ollama models whose blob actually exists. */
export function discoverModels(): ModelEntry[] {
    const manifests = manifestDir();
    if (!fs.existsSync(manifests)) return [];
    const out: ModelEntry[] = [];
    for (const file of walkFiles(manifests)) {
        let data: any;
        try { data = JSON.parse(fs.readFileSync(file, "utf8")); }
        catch { continue; }
        if (!data || typeof data !== "object" || !Array.isArray(data.layers)) continue;
        const rel  = path.relative(manifests, file).split(path.sep);
        if (rel.length < 2) continue;
        const tag    = rel[rel.length - 1];
        const family = rel[rel.length - 2];
        for (const layer of data.layers) {
            if (layer.mediaType !== MODEL_LAYER) continue;
            let digest: string = String(layer.digest || "");
            if (digest.startsWith("sha256:")) digest = digest.slice("sha256:".length);
            const blobPath = path.join(blobDir(), `sha256-${digest}`);
            let st: fs.Stats;
            try { st = fs.statSync(blobPath); } catch { break; }
            out.push({
                name: `${family}:${tag}`,
                family,
                tag,
                size: Number(layer.size ?? st.size),
                digest,
            });
            break;
        }
    }
    out.sort((a, b) => a.name.localeCompare(b.name));
    return out;
}

/** Resolve "family:tag" to absolute blob path on disk. */
export function findBlob(nameTag: string): string | null {
    for (const m of discoverModels()) {
        if (m.name === nameTag) {
            return path.join(blobDir(), `sha256-${m.digest}`);
        }
    }
    return null;
}
