/* Generated by cbindgen from rullama-core. Do not edit by hand. */

#ifndef RULLAMA_FFI_H
#define RULLAMA_FFI_H

/* AUTO-GENERATED — regenerate with scripts/gen-header.sh */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque engine handle. Owns the worker thread + the channel to it.
typedef struct RlModel RlModel;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the last error message for the **calling thread** as a NUL-terminated
// C string, or NULL if none. The pointer is valid until the next FFI call on
// this thread; copy it immediately. Do not free it.
const char *rl_last_error(void);

// Returns this shim's version string (static; do not free).
const char *rl_version(void);

// Frees a C string previously returned by this library (e.g. `rl_model_probe`).
//
// # Safety
// `ptr` must be NULL or a pointer obtained from this library; it must not be
// used after this call.
void rl_free_str(char *ptr);

// Creates an engine handle: spawns its dedicated owning thread.
//
// Returns NULL if the thread could not be spawned (see `rl_last_error`).
RlModel *rl_model_create(void);

// Frees an engine handle: signals the owning thread to stop and joins it,
// guaranteeing the `!Send` engine state is dropped on its own thread.
//
// # Safety
// `m` must be NULL or a handle from `rl_model_create`, not used afterward.
void rl_model_free(RlModel *m);

// Probes the GPU on the handle's owning thread. On success writes a newly
// allocated C string (free with `rl_free_str`) describing the adapter to
// `*out` and returns 0. Negative on error (see `rl_last_error`).
//
// # Safety
// `m` must be a valid handle; `out` must be a valid, writable `*mut c_char`.
int32_t rl_model_probe(RlModel *m, char **out);

// Convenience one-shot: create a handle, probe, free. On success writes a
// newly allocated C string (free with `rl_free_str`) to `*out`, returns 0.
//
// # Safety
// `out` must be a valid, writable `*mut c_char`.
int32_t rl_wgpu_probe(char **out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RULLAMA_FFI_H */
